workflows:
  ios-release:
    name: iOS Release Build - Nota Premiada
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_ID: com.hardsoft.notaPremiada
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Build iOS .ipa
        script: flutter build ipa --release --export-options-plist=ios/ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key:
          key_id: $APP_STORE_API_KEY_ID
          issuer_id: $APP_STORE_ISSUER_ID
          private_key: |
            $APP_STORE_PRIVATE_KEY
        submit_to_testflight: true
