workflows:
  ios-release:
    name: iOS Release Build - Nota Premiada
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_ID: com.hardsoft.notaPremiada
      groups:
        - app_store_credentials
    scripts:
      - name: Clean project
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get
      - name: Build .app
        script: flutter build ios --release --no-codesign
      - name: Create .ipa manually
        script: |
          mkdir -p build/ios/ipa/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -r Runner.ipa Payload
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: @env:APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY
        key_id: @env:APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: @env:APP_STORE_CONNECT_ISSUER_ID
        submit_to_app_store: true
