workflows:
  ios-release:
    name: Build iOS e enviar App Store
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ipa --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: full_key
        bundle_id: com.hardsoft.notaPremiada
        submit_to_testflight: true    # opcional, pode manter para beta testers
        submit_to_app_store: true     # envia para revisão e publicação na loja
