workflows:
  ios-release:
    name: iOS Release
    integrations:
      app_store_connect: CodeMagic API Key  # nome da chave que você salvou no painel
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ipa --release --export-options-plist=ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
