workflows:
  ios-release:
    name: Build iOS e enviar TestFlight
    max_build_duration: 60
    integrations:
      app_store_connect: full_key  # nome da sua integração no Codemagic
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ipa
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
