workflows:
  ios-release:
    name: iOS Release Build - Nota Premiada
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_ID: com.hardsoft.notapremiada
      groups:
        - app_store_credentials  # grupo com as variáveis da API Key da Apple
    scripts:
      - name: Clean project
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get
      - name: Build IPA
        script: flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_app_store: true
