workflows:
  ios-release:
    name: Build iOS e enviar TestFlight
    integrations:
      app_store_connect: manager_key
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ipa --release --export-options-plist=ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
