workflows:
  ios-release:
    name: iOS Release Build - Nota Premiada
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_ID: com.hardsoft.notaPremiada
      groups:
        - app_store_credentials
    scripts:
      - name: Clean project
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get
      - name: Build IPA (com assinatura automática)
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: "@raw:@env:APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY_B64"
        key_id: "KX74AF689U"
        issuer_id: "5d27ba94-ad90-403e-8774-60caae8f435b"
        submit_to_app_store: true
