workflows:
  ios-release:
    name: Build iOS e enviar TestFlight
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ipa --release --export-options-plist=ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key:
          key_id: $APP_STORE_API_KEY_ID
          issuer_id: $APP_STORE_ISSUER_ID
          private_key: $APP_STORE_PRIVATE_KEY
        submit_to_testflight: true
